/* NavAuiShim */
(function(x){x.execute(function(){(function(e){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!e.$Nav)e.$Nav=a("rcx-nav");if(!e.$Nav.make)e.$Nav.make=a})(window)})})(function(){var x=window.AmazonUIPageJS||P,e=x.attributeErrors;return e?e("NavAuiShim"):x}());
;/* P13NSharedSitewideJS */
(function(j){j.execute(function(){(function(){j.register("p13n-sc-math",function(){return Math});j.register("p13n-sc-document",function(){return document});j.register("p13n-sc-window",function(){return window});j.register("p13n-sc-undefined",function(){});j.when("p13n-sc-window").register("p13n-sc-util",function(b){var f=b.ueLogError;typeof f!=="function"&&(f=function(b,f){if(f&&f.message)throw Error(f.message);if(b&&b.message)throw Error(b.message);});var i=function(b,i){f({logLevel:b,attribution:"P13NSharedSitewideJS",
message:"[p13n-sc] "+i})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:b.ue&&b.ue.count||function(){},log:{warn:function(b){i("WARN",b)},error:function(b){i("ERROR",b)}}}})})();j.when("A","jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,f,i,e){var k=i.clearInterval,h={},l,m,d=function(){if(!l){var d=b.interval(function(){var a=d,c=b.now();a!==l?k(a):((!m||c-m>200)&&b.trigger("p13n:heartbeat"),m=b.now())},200);l=d}};return{subscribe:function(g,
a){h[g]||(h[g]=a,b.on("p13n:heartbeat",a),d())},unsubscribe:function(d){h[d]&&(b.off("p13n:heartbeat",h[d]),delete h[d]);b.objectIsEmpty(h)&&(k(l),l=e)}}});j.when("A","jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,f,i){var e=[],k=f(window),h=function(){for(var b=k.scrollTop()+k.height(),f=k.scrollLeft()+k.width(),d=e.length-1;d>=0;d--){var g=e[d],a=g.callback,c=g.$element,n=g.distanceY,g=g.distanceX;if(c.parents("body").size()===0)e.splice(d,1);else if(!c.is(":hidden")){var h=
c.offset();b-n>h.top&&f-g>h.left&&(a.call(null,c[0]),e.splice(d,1))}}e.length===0&&i.unsubscribe("p13n-sc-call-on-visible")};return{register:function(b,m,d){var g=d&&typeof d.distance!=="undefined"?d.distance:0,a=d&&typeof d.distanceY!=="undefined"?d.distanceY:g,c=d&&typeof d.distanceX!=="undefined"?d.distanceX:0;f(b).each(function(){e.push({$element:f(this),callback:m,distanceY:a,distanceX:c})});i.subscribe("p13n-sc-call-on-visible",h);h()}}});j.when("A","jQuery","p13n-sc-call-on-visible","p13n-sc-util",
"p13n-sc-math").register("p13n-sc-view-trigger",function(b,f,i,e,k){var h=function(e){var d=f(e),e=d.attr("data-params"),g=d.attr("data-url");if(e&&g){var e=b.parseJSON(e),a=d.offset(),d=[a.top,a.left,d.height(),f(window).width()];e.elementRect=d.join(",");var c=0,n={cache:!0,crossDomain:!1,data:f.param(e,!1),error:function(a){a=a.status||0;c>=3||a>=400&&a<500||setTimeout(h,200*k.pow(2,c))},global:!1,url:g},h=function(){c+=1;f.ajax(n)};h()}},l=function(e){var d=f(e);if(d.size()===1){var g=d.attr("data-params"),
g=g?b.parseJSON(g):{};if(!(g.allowEmpty!==!0&&d.text().trim().length===0)){var a=d.height();if(!(g.allowEmpty!==!0&&a<5)){a=0;if(typeof g.distance==="number")a=g.distance;d.attr("data-p13n-sc-vt-initialized")||(d.attr("data-p13n-sc-vt-initialized",!0),i.register(e,function(){h(e)},{distance:a}))}}}},e=function(){b.each(f(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(b){l(b)})};j.execute(e);j.when("afterReady").execute("p13n-sc-view-trigger:init",e);return{initializeElement:l}});j.when("jQuery",
"A","p13n-sc-util","p13n-sc-window","p13n-sc-document","ready").register("p13n-sc-logger",function(b,f,i,e,k){function h(a){return a.join("")}function l(a,c){for(var b=[a.widget,":"],d=0;d<a.asins.length;d++){var e=a.asins[d];b.push(e.asin,"@");f.each(e,function(a,c){c!=="asin"&&b.push(c,"=",a,"|")});b.splice(b.length-1,1);b.push(",")}a.asins.length>0&&b.splice(b.length-1,1);c&&(b.push(":","action=",a.action),f.each(a.meta,function(a,c){b.push(",",c,"=",a)}));return h(b)}function m(a,c){var d=b(c).data("p13nAsinMetadata");
if(d&&d.asin){var e=d.asin,g=b(a).data("p13nAsinMetadata");g&&b.extend(!0,d,g[e]);return d}}function d(c,d){var g=new Image;i.count("p13n:logger:attempt",1);g.onerror=function(){a++;i.count("p13n:logger:error",1)};g.src=h(["https:"===k.location.protocol?"https://":"http://",e.ue_furl||"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",d,h(["?",b.param(b(c.featureElement).data("p13nGlobal"))])])}function g(){return a>3?(c||(i.log.warn("impression image load failed too many times, no longer logging impressions"),
i.count("p13n:logger:abort",1),c=!0),!0):!1}var a=0,c=!1,n={},j={},p={logAction:function(a){if(!g())if("featureElement"in a)if("action"in a){var c=b(a.featureElement);a.asins=b.map(b(a.featureElement).find(".p13n-asin").filter(":visible"),function(a){return m(c,a)});a.meta=a.meta||{};var e=c.data("p13nFeatureMetadata");b.extend(!0,a.meta,e);a.widget=c.data(i.constants.DATA_ATTR_P13N_FEATURE_NAME);a.widget in n||(n[a.widget]={});for(var f=e=0;f<a.asins.length;f++)a.asins[f].asin in n[a.widget]||(n[a.widget][a.asins[f].asin]=
!0,e++);a.logOnlyOnNew&&e===0||(e=h(["action/",h([a.widget,"_:",a.action,"@v=",a.eventtime||0,",impressed@v=",e]),"/",l(a,!0)]),a.replicateAsinImpressions&&(f=h(["asin/",l(a,!1)]),e=h(["batch/",e,"$",f])),d(a,e))}else i.log.warn("action missing in eventData for logAction");else i.log.warn("featureElement missing in eventData for logAction")},logAsyncAction:function(a){var c=f.now(),b=typeof a.initialDelay==="number"?a.initialDelay:400,d=typeof a.timeout==="number"?a.timeout:5E3;a.widget in j&&e.clearTimeout(j[a.widget]);
var g=function(){var b=a.isEventComplete(),e=f.now();if(e-c<d&&!b)j[a.widget]=f.delay(g,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=e-c;delete j[a.widget];p.logAction(a)}};j[a.widget]=f.delay(g,b)},impressAsin:function(a){if(!g())if("featureElement"in a)if("faceoutElement"in a){var c=b(a.faceoutElement),e=b(a.featureElement);a.widget=e.data(i.constants.DATA_ATTR_P13N_FEATURE_NAME);a.asins=[m(e,c)];c=h(["asin/",l(a,!1)]);d(a,c)}else i.log.warn("faceoutElement missing in eventData for logAction");
else i.log.warn("featureElement missing in eventData for logAction")}};return p});j.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger","ready").register("p13n-sc-faceout-logger",function(b,f,i,e){var k=function(f,k){var m=b(f),d=b(k);m.length===1&&!m.attr("data-p13n-sc-fl-initialized")&&(m.attr("data-p13n-sc-fl-initialized",!0),i.register(m,function(){e.impressAsin({featureElement:d,faceoutElement:m})}))};f.on("p13n:faceoutsloaded",function(e){b(e).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,
f){k(f,e)})})});j.when("A","jQuery").register("p13n-sc-lazy-image-loader",function(b,f){return{loadImages:function(i){b.executeDeferred();i.find(".p13n-sc-lazy-loaded-img").each(function(e,i){var h=f(i),l=h.find(".a-dynamic-image");l.load(function(){h.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(l)})}}});j.when("jQuery","A","p13n-sc-util","p13n-sc-math","p13n-sc-line-truncator-settings").register("p13n-sc-line-truncator",function(b,f,i,e,k){function h(d){this.$element=d;this.$experimentElement=
b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=d.data("rows");this.lineHeight=k.lineHeight;this.maxRows||i.log.error("Truncation element missing necessary line number data")}var l=/(?=[ \-\/])/,m=/[^\/\-\[\]():\s]/;h.prototype.truncate=function(){var b=this.$element.html();this.$element.append(this.$experimentElement);if(!this.checkLineFit(b)){var e=this.truncateByToken(b);e?(this.$element.html(e),this.$element.attr({title:b})):i.log.error("Unable to successfully truncate line "+b)}this.$experimentElement.remove()};
h.prototype.checkLineFit=function(b){this.$experimentElement.html(b);b=this.$experimentElement.get(0).clientHeight/this.lineHeight;return e.round(b)<=this.maxRows};h.prototype.truncateByToken=function(b){for(var b=b.split(this.getTokenSeparatorRegex()),g=1,a=b.length,c,f,h=0;g!==a;)if(c=e.floor((a+g)/2),f=b.slice(0,c).join("")+"&hellip;",this.checkLineFit(f)){if(a-c<=1){for(h=c;h>0&&!m.test(b[h-1]);)h--;break}g=c}else a=c;return h===0?void 0:b.slice(0,h).join("")+"&hellip;"};h.prototype.getTokenSeparatorRegex=
function(){return this.$element.data("truncateByCharacter")?"":l};return{truncateLines:function(d){d.find(".p13n-sc-truncate").each(function(){var d=new h(b(this));d&&d.truncate()})}}});j.register("p13n-sc-line-truncator-settings",function(){return{lineHeight:19}});j.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-math","p13n-sc-window","p13n-sc-faceout-logger","p13n-sc-lazy-image-loader","p13n-sc-line-truncator").register("p13n-sc-carousel",function(b,f,i,e,k,h,l,m){function d(a){this.$container=
b(a);this.$content=this.$container.find(".p13n-sc-carousel-content");if(this.$container.attr(g))return!1;else this.$container.attr(g,!0);this.devicePixelRatio=k.devicePixelRatio||1;this.itemWidth=this.originalItemWidth=this.$content.children(":first").outerWidth();this.maxItemHeight=0;this.asins=this.$container.data("asins").toString().split(",");this.asinIndex=this.$container.data("asin-index");this.ajaxUrl=this.$container.data("ajax-url");this.lastPositionedCellIndex=0;var a=this.$container.offset(),
c=parseInt(this.$container.css("margin-left"),10);e.abs(a.left)>0&&this.$container.css("margin","0 "+(c-a.left)+"px");this.hasAdditionalProducts()&&this.addLoadingAnimation();var d=this;(this.useNativeScrolling=f.capabilities.touchScrolling)?this.hasAdditionalProducts()&&this.$container.bind("scroll.p13n-sc-carousel",function(){d.handleScroll()}):(this.useTranslate=f.capabilities.transition&&f.capabilities.transform3d,this.offsetX=0,this.transitionClass="",this.$container.bind("touchstart.p13n-sc-carousel",
function(a){d.handleTouchStart(a)}));f.trigger("p13n:faceoutsloaded",this.$container);b(k).bind("resize.p13n-sc-carousel",function(a){d.handleResize(a)});this.handleResize();l.loadImages(this.$container);m.truncateLines(this.$container)}var g="data-p13n-sc-carousel-initialized";b.extend(b.easing,{easeOutQuad:function(a){return-a*(a-2)}});d.prototype={hasAdditionalProducts:function(){return this.asins.length>this.asinIndex+1},handleScroll:function(){if(!this.isLoadingProducts&&this.hasAdditionalProducts()&&
this.maxScroll){var a=this.itemWidth*5;this.maxScroll-(this.useNativeScrolling?this.$container.scrollLeft():this.offsetX)<=a&&this.loadAdditionalProducts()}},loadAdditionalProducts:function(){this.isLoadingProducts=!0;for(var a=[],c=this.asinIndex+1;c<=this.asinIndex+10&&c<this.asins.length;c++)a.push(this.asins[c]);(c=this.$container.data("ajax-params"))||(c={faceoutTemplateClass:this.$container.data("faceout-template-class"),widgetTemplateClass:this.$container.data("widget-template-class"),reftagPrefix:this.$container.data("reftag-prefix"),
auiDeviceType:this.$container.data("aui-device-type"),suppressCurrencyImageFormat:this.$container.data("suppress-currency-image-format")});c.lazyLoadImages=1;c.asins=a.join();c.offset=this.asinIndex+1;var d=this;b.ajax({url:this.ajaxUrl,data:c,success:function(c){d.handleAjaxComplete(c,a.length)},error:function(){d.handleAjaxComplete(null,a.length)}})},handleAjaxComplete:function(a,c){var d=!1;a&&b.isArray(a)&&a.length>0&&(d=b(a.join("")),this.$loadingAnimation.before(d),l.loadImages(d),m.truncateLines(d),
d=!0);this.asinIndex+=c;this.hasAdditionalProducts()||(this.removeLoadingAnimation(),this.$container.unbind("scroll.p13n-sc-carousel"),d=!0);d&&this.positionCells();this.isLoadingProducts=!1},addLoadingAnimation:function(){if(!this.$loadingAnimation)this.$loadingAnimation=b('<div class="p13n-sc-carousel-item p13n-sc-carousel-loading-image a-manually-loaded" style="right: 0px;"></div>');this.$content.append(this.$loadingAnimation)},removeLoadingAnimation:function(){this.$loadingAnimation&&this.$loadingAnimation.remove()},
handleResize:function(){this.useNativeScrolling||(this.$content.removeClass(this.transitionClass),this.$container.stop());var a=this.$container.innerWidth();this.pageSize=e.floor(a/this.originalItemWidth);this.itemWidth=this.originalItemWidth;this.positionCells(0);if(!this.useNativeScrolling)this.offsetX=e.floor(this.offsetX/this.itemWidth)*this.itemWidth,this.applyPosition();this.handleScroll()},positionCells:function(a){for(var c=this.$content.children(),a=a===void 0?this.lastPositionedCellIndex:
a;a<c.length;a++){var b=c.eq(a);this.maxItemHeight=e.max(this.maxItemHeight,b.height())}this.lastPositionedCellIndex=c.length-1;c=c.length*this.itemWidth;this.$content.width(c);this.$content.height(this.maxItemHeight);this.maxScroll=c-this.$container.innerWidth();f.trigger("p13n:faceoutsloaded",this.$container)},handleTouchStart:function(a){a=a.originalEvent.targetTouches[0];this.startTouchX=a.pageX;this.startTouchY=a.pageY;this.startContentX=this.initialOffsetX=this.offsetX;this.scrollState=0;this.$content.removeClass(this.transitionClass);
this.$container.stop();var c=this;b(k).bind("touchmove.p13n-sc-carousel",function(a){c.handleTouchMove(a)});b(k).bind("touchend.p13n-sc-carousel",function(a){c.handleTouchEnd(a)})},handleTouchMove:function(a){var c=a.originalEvent.targetTouches[0];if(this.scrollState===0){var d=e.abs(c.pageX-this.startTouchX),g=e.abs(c.pageY-this.startTouchY);if(d>5&&d>g)this.scrollState=2;else if(g>5&&g>d){this.scrollState=1;b(k).unbind("touchmove.p13n-sc-carousel");b(k).unbind("touchend.p13n-sc-carousel");return}}a.originalEvent.preventDefault();
a=this.startContentX+this.startTouchX-c.pageX;if(a<0||a>this.maxScroll)a=e.max(a,0),a=e.min(a,this.maxScroll),this.startTouchX=c.pageX,this.startContentX=a;this.offsetX=a;this.applyPosition()},handleTouchEnd:function(){b(k).unbind("touchmove.p13n-sc-carousel");b(k).unbind("touchend.p13n-sc-carousel");var a=e.floor(this.startContentX/this.itemWidth);if(this.offsetX<this.startContentX)this.offsetX=(a-this.pageSize)*this.itemWidth;else if(this.offsetX>this.startContentX)this.offsetX=(a+this.pageSize)*
this.itemWidth;this.offsetX=e.max(this.offsetX,0);this.offsetX=e.min(this.offsetX,this.maxScroll);this.offsetX!==this.initialOffsetX&&this.handleScroll();if(this.offsetX!==this.startContentX)a=e.abs(this.offsetX-this.startContentX)/(this.itemWidth*this.pageSize),this.useTranslate?(this.transitionClass="p13n-sc-carousel-transition-"+e.ceil(5*a),this.$content.addClass(this.transitionClass),this.applyPosition()):this.$container.animate({scrollLeft:this.offsetX},{easing:"easeOutQuad",duration:e.ceil(250*
a)})},applyPosition:function(){this.useTranslate?this.$content.css("-webkit-transform","translate3d("+-this.offsetX+"px,0,0)"):this.$container.scrollLeft(this.offsetX)}};j.when("afterReady").execute("p13n-sc-carousel:init",function(){var a={distanceY:-500,distanceX:0};b(".p13n-sc-carousel").each(function(c,b){i.register(b,function(){new d(b)},a)})});return d});j.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math","p13n-sc-lazy-image-loader").register("p13n-sc-list",function(b,
f,i,e,k,h){function l(a){var c=this;c.$container=b(a);if(c.$container.attr(m))return!1;else c.$container.attr(m,!0);c.$cellListContainer=c.$container.find(".p13n-sc-list-cells-container");c.$cellList=c.$container.find(".p13n-sc-list-cells");c.$buttons=c.$container.find(".p13n-sc-list-show-more-buttons");c.$showMoreButton=c.$container.find(".p13n-sc-list-show-more");c.$showMorePartialOverlay=c.$container.find(".p13n-sc-list-partial-overlay");c.$hideButton=c.$container.find(".p13n-sc-list-hide");c.$loader=
c.$container.find(".p13n-sc-list-loader");c.asins=c.$container.data("asins").toString().split(",");c.asinIndex=c.$container.data("asin-index");c.initialCellContainerHeight=0;c.isInitialLoad=!0;c.requestSize=(c.asinIndex+1)*2;c.buttonState=g;if(c.hasAdditionalProducts()){c.$buttons.removeClass("a-hidden");c.$buttons.bind("click",function(a){c.buttonsWereTapped(a)});var a=c.$cellListContainer.find(".p13n-sc-list-item:last-child").height(),e=k.floor(a*d);c.initialCellContainerHeight=c.$cellListContainer.height()-
a+e;c.$showMorePartialOverlay.css({height:e,top:-e});c.$cellListContainer.css({height:c.initialCellContainerHeight,overflow:"hidden"});c.loadAdditionalProducts()}h.loadImages(c.$container)}var m="data-p13n-sc-list-initialized",d=0.25,g=0;l.prototype={hasAdditionalProducts:function(){return this.isInErrorState?!1:this.asins.length>this.asinIndex+1},loadAdditionalProducts:function(){var a=this;if(!a.isLoadingProducts&&a.hasAdditionalProducts()&&!a.isInErrorState){a.isLoadingProducts=!0;for(var c=[],
b=a.asinIndex+1;b<=a.asinIndex+a.requestSize&&b<a.asins.length;b++)c.push(this.asins[b]);(b=this.$container.data("ajax-params"))||(b={faceoutTemplateClass:this.$container.data("faceout-template-class"),widgetTemplateClass:this.$container.data("widget-template-class"),reftagPrefix:this.$container.data("reftag-prefix"),suppressCurrencyImageFormat:this.$container.data("suppress-currency-image-format"),imageWidth:a.$container.data("image-width")||"",imageHeight:a.$container.data("image-height")||"",auiDeviceType:a.$container.data("aui-device-type")});
b.lazyLoadImages=1;b.asins=c.join();b.offset=this.asinIndex+1;var d=a.$container.data("ajax-url");f.ajax(d,{method:"get",params:b,success:function(b){a.handleAjaxComplete(b,c.length)},error:function(){a.handleAjaxComplete(null,c.length)}})}},handleAjaxComplete:function(a,c){this.asinIndex+=c;this.isInitialLoad=!1;if(a&&b.isArray(a)&&a.length>0){var d=b(a.join(""));this.$cellList.append(d);h.loadImages(d)}else this.isInErrorState=!0,e.log.error("[p13n-sc] List View partial endpoint returned an item that was not an array of cells.");
this.isLoadingProducts=!1;this.shouldOpenOnLoad&&(this.hideLoader(),this.animateOpen())},buttonsWereTapped:function(a){this.buttonState===g?this.showMoreWasTapped():this.buttonState===1?this.hideWasTapped():this.buttonState===2&&(a.pageX-b(a.currentTarget).position().left>this.$buttons.width()/2?this.hideWasTapped():this.showMoreWasTapped())},showMoreWasTapped:function(){e.count("p13n:sc:list:show-more",(e.count("p13n:sc:list:show-more")||0)+1);this.isLoadingProducts&&this.isAtMaxHeight()||this.isInitialLoad?
this.showLoader():this.animateOpen()},hideWasTapped:function(){e.count("p13n:sc:list:hide",(e.count("p13n:sc:list:hide")||0)+1);this.animateClosed()},animateOpen:function(){var a=this;a.loadAdditionalProducts();f.animate(a.$cellListContainer,{height:a.$cellList.height()},1E3,"ease-out",function(){a.configureButtons()})},animateClosed:function(){var a=this;a.$cellListContainer.animate({height:a.initialCellContainerHeight},{duration:500,queue:!1,complete:function(){a.configureButtons()}});b("html, body").animate({scrollTop:a.$container.offset().top+
a.initialCellContainerHeight+a.$buttons.outerHeight()-b(window).height()},{duration:500,queue:!1})},showLoader:function(){this.shouldOpenOnLoad=!0;this.$loader.removeClass("a-hidden");this.$showMoreButton.addClass("a-hidden");this.$hideButton.addClass("a-hidden")},hideLoader:function(){this.shouldOpenOnLoad=!1;this.$loader.addClass("a-hidden");this.$showMoreButton.removeClass("a-hidden");this.$hideButton.removeClass("a-hidden")},isAtMaxHeight:function(){return this.$cellListContainer.height()===this.$cellList.height()},
isAtMinHeight:function(){return this.$cellListContainer.height()===this.initialCellContainerHeight},configureButtons:function(){var a=2;this.isAtMinHeight()?a=g:this.isAtMaxHeight()&&!this.isLoadingProducts&&(a=1);this.setButtonState(a)},setButtonState:function(a){this.buttonState=a;this.$buttons.removeClass("p13n-sc-both-state p13n-sc-show-more-state p13n-sc-hide-state");a===g?this.$buttons.addClass("p13n-sc-show-more-state"):a===1?this.$buttons.addClass("p13n-sc-hide-state"):a===2&&this.$buttons.addClass("p13n-sc-both-state")}};
j.when("afterReady").execute("p13n-sc-list:init",function(){var a={distanceY:-500,distanceX:0};b(".p13n-sc-list").each(function(c,b){i.register(b,function(){new l(b)},a)})});return l});j.when("A","jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,f,i,e,k,h){function l(b,a){var c=b.getAttr("pageNumber"),d=b.dom.$container;d.data("p13nPreviousPage",c);k.logAsyncAction(f.extend(!0,{},{featureElement:d,isEventComplete:function(){return d.find(".a-carousel-card-empty").size()===
0&&!b.getAttr("animating")},meta:{page:c},replicateAsinImpressions:!0},a))}function m(b){d(b)&&e.register(b.dom.$container,function(){l(b,{action:"view"})})}var d=function(b){return typeof b==="undefined"?!1:b.dom.$container.data(h.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(i.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&m(b)});b.on("a:carousel:init",function(b){m(b.carousel)});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage",
"click",function(b){b=i.getCarousel(b.target);l(b,{action:"next_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage","click",function(b){b=i.getCarousel(b.target);l(b,{action:"prev_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(b){b=i.getCarousel(b.target);l(b,{action:"start_over",meta:{op:b.dom.$container.data("p13nPreviousPage")}})});b.on("a:carousel:change:pageSize",function(b){b=
b.carousel;d(b)&&b.dom.$container.hasClass("a-carousel-initialized")&&l(b,{action:"resize",logOnlyOnNew:!0})})})})})(function(){var j=window.AmazonUIPageJS||P,b=j.attributeErrors;return b?b("P13NSharedSitewideJS"):j}());
;/* RetailSearchAutocompleteAuiAssets */
(function(E){E.execute(function(){if(!window.$SearchJS&&window.$Nav)window.$SearchJS=$Nav.make("sx");if(window.$SearchJS){$SearchJS.when("jQuery").run("autocomplete-lib",function(a){(function(v,D){var U;function Q(d,c,g,f,k){d.append(a('<input type="hidden"/>').attr(k?"class":"id",c).attr("name",g).attr("value",f))}function F(d,c){var a=d.find('option[value$="'+c+'"]');a.length>1&&(a=a[0]);return a}function ya(d,c,g){var f=r;d=="search-alias=aps"&&!c&&(c=F(f,d).text());a("#"+ga).css("visibility",
"hidden");a(za).text(c);f.val(d);g||(opt.sb.focus(),V(opt.form,d))}function V(a,c,g,f,k){var l=g!=null&&f;if(l||c!=null){var j=a.attr("action"),q=f.type===B.getType();if(!q&&!l){var G;!c||!c.length||(G=c.indexOf("="))==-1?f="":(f=c.substr(G+1),k=f.indexOf("-")+1,q=f.substr(0,3),f=k?q:q+f.charAt(k));c="dd_"+f}else c=g+"_"+(q?f.alias:f.sgIndex),q&&(c+="_"+B.buildDepartmentReftagSuffix(f)),c+="_"+k;f=c;E.test(j)?j=l&&W.test(j)?j.replace(W,"$1_"+f):j.replace(E,"ref=nb_sb_"+f):(j.charAt(j.length-1)!="/"&&
(j+="/"),j+=f);a.attr("action",j)}}function Ua(a,c,g){var f,k,l,j,q,G=c||0;return{callSuggestionsService:function(a){f=a;k="&noCacheIE="+(new Date).getTime();l=document.getElementsByTagName("head").item(0);j="JscriptId"+G;q=document.createElement("script");q.setAttribute("type","text/javascript");q.setAttribute("charset","utf-8");q.setAttribute("src",f+k);q.setAttribute("id",j);l.appendChild(q)},cleanup:function(){try{l.removeChild(q)}catch(a){}},keywords:a,counter:G,imeEnhUsed:g}}var E=/(ref=[-\w]+)/,
ha=/^\s+/,ia=/\s+/g,W=/(dd_[a-z]{3,4})(_|$)[\w]*/,Va=/\{department\}/g,Wa=/\+/g,Xa=/search-alias\s*=\s*([\w-]+)/,Ya=/node\s*=\s*([\d]+)/,Za=/bbn\s*=\s*([\d]+)/,$a=/^me=([0-9A-Z]*)/,za="#ddCrtSel",ga="searchDropdown_pop_conn",ja=Object.prototype.toString,r;U=typeof uet=="function"&&typeof uex=="function";a.isArray=a.isArray||function(a){return ja.call(a)==="[object Array]"};var ab=function(d,c,g,f){var k=a(g),l=c.pe||d.parent(),j=null,q=!1,G=!1,d=function(){},x=a.extend({},{afterCreate:d,beforeShow:d,
afterShow:d,beforeHide:d,beforeHtmlChange:d,afterHtmlChange:d,onWindowResize:d},f),s=function(a){x.beforeHtmlChange.call(k,a);k.html(a);x.afterHtmlChange.call(k,a)},r=function(){x.beforeShow.call(k,j);k.show();j&&j.show();x.afterShow.call(k,j)},t=function(){q=!0;G&&r();x.afterCreate.call(k,j)};$Nav.when("nav.inline").run("SearchSuggestSetup",function(){a("#nav-bar-left").length===1&&!a.isArray(c.src)?$Nav.when("nav.createFlyout").run("SearchSuggestFlyout",function(a){j=a({name:"Search Suggest",content:k,
className:"srch_sggst_flyout",align:{base:l,from:"bottom left",to:"top left"},onAlign:function(){var a=l.width();k.css({width:a})}});t()}):setupStatic()});this.getNode=function(){return k};this.html=function(a){s(a);return this};this.setupStatic=function(){k.appendTo(l);a(v).resize(function(a){x.onWindowResize.call(k,a)});t()};this.visible=function(){return q?j?j.isVisible():k.css("display")!="none":!1};this.hide=function(){q?(x.beforeHide.call(k,j),j&&j.hide(),k.hide(),s("")):G=!1;return this};this.show=
function(){q?r():G=!0;return this}},ka=function(a){var c,g,f,k,l=0,j=0;this.keydown=function(a){k=!1;l!=j&&(l=j=0);return a?f=a:f};this.keyup=function(f,l){if(f!=D)if(g=f,c&&c.length>0&&(g==8||g==46))c=c.substring(0,c.length-1),j==1&&(j=0),k=!0,a&&a(l&&l.length>0?l+c:c);else if(g>=65&&g<=90){var r=String.fromCharCode(g);c+=r;k=!0;j==1?j=0:a&&a(l&&l.length>0?l+c:c)}return g};this.isImeInput=function(){return f==229||f==197};this.reset=function(a){a&&l==1?l=0:(f=g=D,c="");a&&(k=!1)};this.isValidKey=
function(){return k};this.setFlag=function(){j=l=1}},bb=function(d,c){function g(a){a!==D&&(j=q=a,d.val(a));return d.val().replace(ha,"").replace(ia," ")}function f(a){a!==D&&(r=a);return r}function k(a){var d=g();if(d!=j&&(a||d!=q))j=d,s&&s.reset(!0),f(d),c.change(d)}function l(){return x&&c.opt.imeEnh&&s.isValidKey()}var j,q,r,x=!1,s=c.opt.imeEnh&&new ka(function(a){f(a);c.change(a)}),v=!1;U&&ue.tag(d.get(0)===document.activeElement?"iss-late":"iss-on-time");d.keydown(function(a){var d=a.keyCode,
f=d==38?-1:d==40?1:0;s&&s.keydown(d);x=d==229||d==197?!0:d>=48&&d<=57||d>=65&&d<=90?!1:x;f&&(c.adjust(f),g()!=""&&a.preventDefault());c.opt.doCTWKeydown&&c.opt.doCTWKeydown(a)}).keyup(function(a){a=a.keyCode;switch(a){case 13:c.hide();break;case 27:return c.dismiss();case 37:case 38:case 39:case 40:break;default:s&&s.isImeInput()?s.keyup(a,j):k(!0)}}).keypress(function(a){switch(a.keyCode){case 13:return c.submitEnabled();default:c.keyPress()}}).select(function(){s&&s.setFlag()}).blur(function(){c.dismiss();
s&&s.reset()}).focus(function(){s&&s.reset()}).click(function(){c.click(g());s&&s.reset()});d.bind("compositionstart",function(){v=!0}).bind("compositionend",function(){setTimeout(function(){return function(){v=!1}}(),200)});r=j=g();this.keyword=function(a){return g(a)};this.userInput=function(a){return f(a)};this.size=function(){return c.newDesign?{width:a("#nav-iss-attach").outerWidth(),height:a("#nav-iss-attach").outerHeight()}:{width:d.outerWidth(),height:d.outerHeight()}};this.pos=function(){return c.newDesign?
a("#nav-iss-attach").position():d.position()};this.offset=function(){return d.offset()};this.parent=function(){return d.parent()};this.hasFocus=function(){return d.get(0)===document.activeElement};this.cursorPos=function(){var a=d.get(0);if("selectionStart"in a)return a.selectionStart;else if(document.selection){a.focus();var c=document.selection.createRange(),f=document.selection.createRange().text.length;c.moveStart("character",-a.value.length);return c.text.length-f}return-1};this.update=k;this.isImeEnhUsed=
l;this.blur=function(){d.blur()};this.focus=function(){var a=d.val();d.focus().val("").val(a)};this.keydown=function(a){d.keydown(a)};this.click=function(a){d.click(a)};this.onFocus=function(a){d.focus(a)};this.onBlur=function(a){d.blur(a)};this.isImeUsed=function(){return x};this.shouldAddIMEReftag=function(){return c.opt.ime&&v||l()}};v.AutoComplete=function(d){function c(e){a.extend(b,Ba,e);L=b.isNavInline&&L;Ca=B.createDataArray(a,b);e=b.src;X=a.isArray(e);g(b,"sb");if(b.sb){w=new bb(b.sb,{adjust:k,
hide:j,dismiss:q,change:X?G:x,submitEnabled:s,keyPress:U,click:l,newDesign:L,opt:b});g(b,"pe");y=new ab(w,b,'<div id="srch_sggst" style="display:none"/>',{afterCreate:la,onWindowResize:la,beforeShow:la});g(b,"form");g(b,"valInput");g(b,"dd");g(b,"submit");r=b.dd;b.protocol=b.protocol||v.document.location.protocol||"http:";r&&(Y=r.val());X&&(M=e[0],Da=e[1],b.sb.removeAttr("style"),y.setupStatic());if(b.submit)f("disabled"),b.submitImgDef=b.submit.attr("src"),b.submitToggle=b.submitImgDef&&b.submitImg;
b.ime&&v.setInterval(function(){w.update()},20);$SearchJS.importEvent("navbarPromos");$SearchJS.when("navbarPromos").run("autocomplete-navbarPromos",function(){R=v.navbar.issPromotions(3)})}}function g(e,b,n){if(n=e[b])if((n=a(n))&&n.length)return e[b]=n;delete e[b]}function f(e){b.submit.prop?b.submit.prop("disabled",e):b.submit.attr("disabled",e)}function k(e){if(!(C<=0))try{ma(a("#"+b.sugPrefix+u)),e>0&&u>=C-1?u=-1:e<0&&u<0?u=C-1:u+=e,Ea(!0)}catch(H){}}function l(e){e.length?b.triggerISSOnClick&&
!y.visible()&&a("#navFooter")&&a("#navFooter").is(":visible")&&na():oa()}function j(){!b.ime&&Z()}function q(){return y.visible()?(setTimeout(function(){return function(){Z()}}(),300),u=-1,$=="sugg"&&pa(),!1):!0}function G(e){A=[];if(e.length){N=-1;if(b.multiword)for(var a=t(K()),a=RegExp("(^|(?:\\s))"+a,"i"),n=0,I=M.length,c;n<I&&A.length<b.maxSuggestions;n++)c=M[n],t(c).match(a)&&(A.push({keyword:c,i:n}),N==-1&&(N=n));else{I=0;c=M.length-1;for(var d=-1,o="",a=t(K()),f=a.length;I<=c;)d=Math.floor((I+
c)/2),o=t(M[d]).substr(0,f),o<a?I=d+1:(c=d-1,o==a&&(N=d));if(N!=-1){I=N;do A.push({keyword:M[I],i:I}),++I;while(A.length<b.maxSuggestions&&(n=M[I])&&!t(n).indexOf(a))}}C=A.length;Fa(e);W();Aa()}else oa();S=null;u=-1}function x(e){(new Date).getTime();var a=w.isImeEnhUsed();S&&(clearTimeout(S),S=null);var n=Ga,c=!e||!e.length;c&&w.isImeUsed()&&(n=200);S=setTimeout(function(){return function(){c?oa():b.imeEnh?na(e,a):na();S=null;u=-1}}(),n)}function s(){if($=="promo"&&u>-1)return document.location.href=
R[u].href,!1;var e=b.submit;if(e)return e.prop?!e.prop("disabled"):!e.attr("disabled")}function U(e){qa&&qa(e)}function t(e){return b.normalize?b.normalize(e):e.toLowerCase()}function W(){var e="disabled";if(C){var a=t(A[0].keyword),n=t(K());if(a.length==n.length&&!(b.multiword?Ha(a,n):t(a).indexOf(t(n))))Ia(N),e=""}f(e)}function Aa(){if(b.manualOverride&&!C){var e=K();if((e=b.manualOverride(e))&&e.length)e=Ja(e),Ka(),La(e),f("")}}function oa(){if(!L||!R||R.length==0)Z(),ra();else{C=R.length;$="promo";
y.html("");ra();y.show();h='<ul class="promo_list">';for(i=0;i<C;i++)p=R[i],h+='<li id="'+b.sugPrefix+i+'" onclick="document.location.href=\''+p.href+"'\">",h+='<div class="promo_image" style="background-image: url(\''+p.image+"');\"></div>",h+='<div class="promo_cat">'+p.category+"</div>",h+='<div class="promo_title">'+p.title+"</div>",h+="</li>";h+="</ul>";y.html(h);v.navbar.logImpression("iss");for(i=0;i<C;++i)a("#"+b.sugPrefix+i).mouseover(Ma).mouseout(Na)}}function ga(e){if(!(!b.isDigitalFeaturesEnabled&&
!sa||e.length!=a(Ba.sb).val().length)){a("#searchDropdownBox option");var H=[],n=RegExp("\\b"+e.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")+"(.*)","i");e.length>=B.getMinNumOfChars()&&(a.each(Ca,function(e,a){if(H.length===B.getMaxNumOfResults())return!1;if(n.test(a.triggerWords)||n.test(a.name))B.logImpression(a.alias),a.position=H.length===0?0:H.length+1,H.push(a),C++,J>0&&J++}),a.each(H,function(e){A.splice(e,0,H[e])}))}}function Fa(e){var H=b.sugPrefix,n="#"+H;b.imeSpacing&&w.isImeUsed();aa()||
b.deepNodeISS&&b.deepNodeISS.searchAliasAccessor();y.html("");ga(e);var c="";if(C>0)ra(),y.show(),!X&&!L&&(c+='<div id="sugdivhdr"> '+b.sugText+"</div>");else if(b.noMatch){var d=a("#"+b.noMatch);y.html("");y.getNode().append(d.clone().attr("class","suggest_link suggest_nm").css({display:"block"}));y.show();b.submitToggle&&b.submit.attr("src",b.submitImg)}else Z();for(i=0;i<C;i++){d=A[i];i>0&&A[i-1].type!==d.type&&(c+='<div class="sx_line_holder" />');var f=d,o=e,d=H,j=i,k="",g="",l=f.type===B.getType();
if(l){g=f;f="";o=ca(g,o,"name");g=o+(g.alias!=="gift-cards"&&g.alias!=="digital-text"?" Store":"");switch(Oa){case 0:f='<span class="sx_category_name_highlight">Shop the '+g+"</span>";break;case 1:f='Shop the <span class="sx_category_name_highlight">'+g+"</span>";break;case 2:f='go to <span class="sx_category_name_highlight">'+o+"</span>";break;default:f='<span class="sx_category_name_highlight">'+o+"</span>"}o=f}else if(f.alias){var g=f,q=f=void 0;b.deptText?(da()?(f='<span class="suggest_category_without_keyword">',
q='<span class="sx_category_name_highlight">'+g.categoryName+"</span>"):b.xcatSuggestionImprovementFlag==ta&&!O?(f=ca(g,o)+" <span>",q='<span class="sx_category_name_highlight">'+g.categoryName+"</span>"):(f=ca(g,o)+' <span class="suggest_category">',q=g.categoryName),o=f+b.deptText.replace(Va,q)+"</span>"):o=g.categoryName}else o=ca(f,o);g=o;o=j==J+1&&J>0;!l&&b.xcatSuggestionImprovementFlag!=ka&&J>0&&!O&&o&&(k+='<div class="sx_line_holder" />');l="suggest_link";j==0&&ja&&(l+=" imeSpacing");k+='<div id="'+
(d+j)+'" class="'+l+'">'+g+"</div>";c+=k}C>0&&!L&&(c+='<div id="sugdivhdr2" align="right">&nbsp;</div>');(e=c)&&y.html(e);ua==0&&A.length>0&&(ua=(new Date).getTime()-Pa+Ga);r&&(Y=r.val());Qa=Ra(Y);for(e=0;e<C;++e)a(n+e).mouseover(Ma).mouseout(Na).click(ha);b.doCTWDisplay&&b.doCTWDisplay();n=A[0];if(b.xcatSuggestionImprovementFlag==ta&&!O&&!T&&n){e=!1;if((b.isDigitalFeaturesEnabled||sa)&&n.hasOwnProperty("type"))e=n.type===B.getType();if(!e&&!n.sn)n.alias=D,n.categoryName=D}}function ra(){b.noMatch&&
(a("#"+b.noMatch).hide(),b.submitToggle&&b.submit.attr("src",b.submitImgDef))}function ha(){u=parseInt(this.id.substr(6),10);var e=w.shouldAddIMEReftag()?"ime_":D;pa(e);y.hide();va?v.setTimeout(function(){b.form.submit()},10):b.form.submit()}function pa(e){var c,n,d;if(u>=0)d=ea&&u==0?A[1]:A[u],K(d.keyword),c=d.alias,n=d.categoryName;if(X)u>=0?(Ia(d.i),f("")):(W(),Aa());else{var g=r,j,o;if(g){o=c?"search-alias="+c:Y;j=o==ba||Y==ba?null:ba;c&&(c=F(g,o),ba=null,c.length||(g.append(a("<option/>").attr("value",
o).text(n)),ba=o));try{va=!1,a(za).length&&ya(o,n,!0),g.val(o)}catch(k){va=!0}j&&F(g,j).remove()}c=a("#issprefix");n=B.getType();d?(g="ss_",j=w.userInput(),e&&(g+=e),V(b.form,null,d&&d.source&&d.source[0]=="fb"?g+"fb":d.alias?g+"c":b.sc&&d&&d.sc?g+"sc":d.type===n?g+n:g+"i",d,j.length),j=j+","+Qa+","+ua,c.length?c.attr("value",j):Q(b.form,"issprefix","sprefix",j)):c.remove()}}function la(e){if(!e){var e=w.pos(),a=w.size();this.css({width:a.width,top:e.top+a.height,left:e.left})}}function Ma(){this.style.cursor=
L==!0?"pointer":"default";ma(a("#"+b.sugPrefix+u));u=parseInt(this.id.substr(b.sugPrefix.length),10);Ea(!1)}function Na(){ma(a(this));u=-1}function ma(e){e.removeClass("suggest_link_over")}function Ea(e){$=="sugg"&&e&&pa();a("#"+b.sugPrefix+u).addClass("suggest_link_over")}function Ha(e,a){var b=t(e).search(RegExp("(^|(?:\\s))"+t(a),"i"));return b<=0?b:b+1}function ca(e,a,c){e=c?e[c]:e.keyword;c=b.multiword?Ha(e,a):t(e).indexOf(t(a));if(c!==-1)a=a.length,e=[e.substr(0,c),"<b>",e.substr(c,a),"</b>",
e.substr(c+a)].join("");return e}function Z(){$=="sugg"&&z&&(z.cleanup(),z=null);C=0;y.hide();u=-1}function Ia(e){e=Da[e];b.valInput&&b.valInput.length?b.valInput.attr("value",e):(e=Ja(e||location.href),Ka(),La(e))}function Ja(e){for(var e=e.split("?"),a=e.length>1?e[1]:D,a=a?a.split("&"):[],b=a.length,c;b-- >0;)c=a[b].split("="),a[b]={name:c[0],value:c[1].replace(Wa," ")};return{uri:e[0],formParams:a}}function Ka(){b.form.find(".frmDynamic").remove()}function La(a){b.form.attr("action",a.uri);for(var c=
0;c<a.formParams.length;c++){var d=a.formParams[c];Q(b.form,"frmDynamic",d.name,unescape(decodeURIComponent(d.value)),1)}}function K(a){return w.keyword(a)}function aa(a){if(a)ya(a);else return Ra(r.attr("value"))}function Ra(a){return(a=a.match(Xa))?a[1]:null}function ia(a){var c=b.aliases,d;if(d=c)if(!(d=c==="*")){a:{d=0;for(var f=c.length;d<f;d++)if(c[d]==a){a=d;break a}a=-1}d=a>=0}return d}function Sa(a,b,c,d,f,g,j){a.push({keyword:c,sc:b[g]&&b[g].sc?!0:!1,source:b[g].source,alias:d,categoryName:f,
sgIndex:g,xcatIndex:j})}function da(){return b.xcatSuggestionImprovementFlag==cb&&!O}function wa(e){return!e?a(r.children()[0]).text():(e=a(F(r,"search-alias="+e)))&&e.length?a.trim(e.text()):D}function na(e,c){Pa=(new Date).getTime();z&&z.cleanup();if(fa&&w.hasFocus()){var d=aa()||(b.deepNodeISS?b.deepNodeISS.searchAliasAccessor():null),f=e||K(),g=[],j=function(){a.each(arguments,function(a,e){g.push(e)})},o,k;ia(d)?(b.qs&&(o=w.cursorPos(),o>-1&&o<f.length&&(k=f.substring(o),f=f.substring(0,o))),
j(b.protocol,"//",b.src,"?","method=completion","&q=",encodeURIComponent(f),"&search-alias=",d,"&client=",b.cid,"&mkt=",b.mkt,"&fb=",b.fb,"&xcat=",b.xcat,"&x=updateISSCompletion"),k&&j("&qs="+encodeURIComponent(k)),b.np&&j("&np="+b.np),b.sc&&j("&sc=1"),z&&z.cleanup(),z=new Ua(f,db++,c),z.callSuggestionsService(g.join(""))):Z()}}var b={},M,Da,u=-1,A=[],C=0,S=null,ja=0,z=null,N=-1,Y,ba,va=!1,X,w,qa,xa,y,fa=!0,R=[],$="sugg",L=a("#navbar").hasClass("nav-beacon"),Ba={sb:"#twotabsearchtextbox",form:"#navbar form[name='site-search']",
dd:"#searchDropdownBox",cid:"amazon-search-ui",action:"",sugPrefix:"issDiv",sugText:"Search suggestions",xcat:0,fb:0,imeSpacing:0,maxSuggestions:10},ea=!1,ka=0,cb=1,ta=2,J=-1,T=!1,O=!1,Pa,ua=0,Qa,Ga=100,db=0,Ta=!1,Oa=0,sa=!1,Ca=D;d&&c(d);b.form&&b.form.submit(function(){var a=t(K()),c="ref=nb_sb_noss",d=0;if(!(u>-1)){var f=A;if(f.length>0)for(c="ref=nb_sb_noss_2";d<f.length;){if(t(f[d].keyword)==a){c="ref=nb_sb_noss_1";break}d++}b.form.attr("action",b.form.attr("action").replace(E,c))}});return{suggest:function(a){xa=
a},keypress:function(a){qa=a},submit:function(a){b.form.submit(a)},blur:function(){w.blur()},keyword:K,merchant:function(){var a=r.attr("value").match($a);return a?a[1]:null},searchAlias:aa,searchNode:function(){var a=r.attr("value").match(Ya);return a?a[1]:null},bbn:function(){var a=r.attr("value").match(Za);return a?a[1]:null},stop:function(){fa=!1;requestedKeyword="";z&&(z.cleanup(),z=null)},start:function(){fa=!0},encoding:function(){var a=b.form.find("input[name^='__mk_']");if(a.length)return[a.attr("name"),
a.val()]},focus:function(){w.focus()},offset:function(){return w.pos()},keydown:function(a){w.keydown(a)},isImeEnhUsed:function(){return Ta},triggerImeEnh:function(){return w.isImeUsed()&&b.ime&&a.browser.msie},haveCategorySuggestions:function(){return J>0||T},isDigitalFeaturesEnabled:function(){return b.isDigitalFeaturesEnabled===1},setDepartmentResultStyle:function(a){Oa=a},enableDepartment:function(){sa=!0},onFocus:w?w.onFocus:function(){},onBlur:w?w.onBlur:function(){},cursorPos:w?w.cursorPos:
function(){return-1},initStaticSuggestions:function(a,b,d,f,g,j,o,k,l,q){c({form:b,ime:l,multiword:q,noMatch:k,sb:a,src:[j,o],submit:f,submitImg:g,valInput:d})},initDynamicSuggestions:function(a,b,d,f,g,j,o,k,l,q){c({aliases:j,dd:d,deptText:k,form:b,handler:o,ime:g==6||g==3240,mkt:g,sb:a,sc:q,src:f,sugText:l})},updateAutoCompletion:function(){if(z&&fa&&completion.length&&(completion[0]=completion[0]||"",z.keywords=z.keywords||"",completion[0].toLowerCase()===z.keywords.toLowerCase()&&(Ta=z.imeEnhUsed,
z.cleanup(),z=null,w.hasFocus()))){var a=completion[1],c=completion.length>2?completion[2]:[],d,f=a.length,g=[],j=0,k,l=!aa()&&b.deepNodeISS&&b.deepNodeISS.searchAliasAccessor(),q=l&&(wa(l)||b.deepNodeISS&&b.deepNodeISS.searchAliasDisplayNameAccessor());J=0;T=ea=!1;for(O=l&&q;g.length<b.maxSuggestions&&j<f;){k={keyword:a[j],sc:c[j]&&c[j].sc?!0:!1,sgIndex:j};if(O)k.alias=l,k.categoryName=q;g.push(k);d=(c&&c.length?c[j].nodes:[])||[];if(d.length){k=g;var r=c,u=j,s=a.length,t=void 0,t=void 0,v=0,y=0,
x=0,D=a[u];d=(r&&r.length?r[u].nodes:[])||[];if((t=r[u].source)&&t.length)for(v=0;v<t.length;v++)if(t[v]==="fb"){s==1&&da()?ea=!0:k.pop();T=!0;break}if(b.xcatSuggestionImprovementFlag==ta&&!O&&!T){var s=k,x=r,t=D,v=u,Q=aa(),B=wa(Q);if(s[0].alias||s[0].categoryName)s[0].sn=!0;else{var F=s[0];F.alias=Q;F.categoryName=B}Q!="aps"&&(Sa(s,x,t,"aps",wa("aps"),v,1),b.maxSuggestions+=1);x=k.length}for(m=d.length;y<m&&y<4&&k.length<b.maxSuggestions;)t=d[y],Sa(k,r,D,t.alias,t.name,u,x),++y,++x;J=k.length-1}j==
0&&J>0&&da()&&!ea&&(g.push(g[0]),b.maxSuggestions+=1);++j}C=g.length;A=g;Fa(completion[0]);xa&&(a=xa,c=completion[0],f=A.slice(),T&&da()&&f.splice(0,1),a(c,f))}},init:c}};U&&uet("cf","iss-init-pc",{wb:1})})(window);$SearchJS.publish("search-js-autocomplete-lib")});var B=function(){var a={},v=[["instant-video","Amazon Instant Video",["Amazon","Instant","Video","movies","rentals"]],["prime-instant-video","Prime Instant Video","prime,movies,instant,video,free,streaming,netflix".split(",")],["appliances",
"Appliances",["Appliances"]],["mobile-apps","Apps for Android",["Apps","Android","mobile"]],["arts-crafts","Arts, Crafts & Sewing",["arts","crafts","sewing"]],["automotive","Automotive",["automotive","cars"]],["baby-products","Baby Products",["baby","products"]],["beauty","Beauty",["beauty","makeup","hair"]],["stripbooks","Books",["books","textbooks","rentals"]],["mobile","Cell Phones & Accessories","cell,phones,mobile,cases,iphone,galaxy,nexus".split(",")],["collectibles","Collectibles & Fine Art",
"collectibles,fine,art,coins,memorabilia,paintings,wall art".split(",")],["computers","Computers",["computers","pc","laptop","desktop"]],["electronics","Electronics",["electronics"]],["financial","Credit Cards",["credit","cards"]],["gift-cards","Gift Cards Store",["gift","cards"]],["grocery","Grocery & Gourmet Food",["grocery","gourmet","food"]],["hpc","Health & Personal Care",["health","personal","care"]],["garden","Home & Kitchen",["home","kitchen","furniture","art"]],["industrial","Industrial & Scientific",
["Industrial","Scientific"]],["digital-text","Kindle Store",["kindle","store","ebooks","books"]],["magazines","Magazine Subscriptions",["magazines","subscriptions"]],["movies-tv","Movies & TV","movies,tv,dvds,vhs,video,blu ray,bluray,blu-ray".split(",")],["digital-music","MP3 Music",["mp3","music"]],["popular","Music",["music","cds","autorip","vinyl"]],["mi","Musical Instruments",["musical","instruments","guitars","dj"]],["office-products","Office Products",["office","products","school","toner"]],
["lawngarden","Patio, Lawn & Garden",["patio","lawn","garden"]],["pets","Pet Supplies","pet,supplies,dogs,cats,birds,fish".split(",")],["software","Software",["software"]],["sporting","Sporting & Outdoors",["sporting","outdoors","sports"]],["tools","Tools & Home Improvement",["tools","home","improvement"]],["toys-and-games","Toys & Games",["toys","games"]],["videogames","Video Games","video,games,xbox,ps3,ps4,wii,playstation".split(",")],["wine","Wine",["wine"]],["pantry","Prime Pantry",["prime",
"pantry"]]],D=[["fashion","Clothing, Shoes & Jewelry","clothing,clothes,luggage,hats,shirts,jacket,wallets,sunglasses,jewelry,shoes,handbags,sandals,boots,watches".split(",")],["fashion-mens","Men's Clothing, Shoes & Jewelry","mens,clothing,clothes,shoes,jewelry,mens clothing,mens shoes,mens jewelry,mens watches".split(",")],["fashion-womens","Women's Clothing, Shoes & Jewelry","womens,clothing,clothes,shoes,jewelry,womens clothing,womens shoes,womens jewelry,womens watches".split(",")],["fashion-baby",
"Baby Clothing, Shoes & Jewelry","baby,clothing,clothes,shoes,jewelry,baby clothing,baby shoes,baby jewelry".split(",")],["fashion-boys","Boys Clothing, Shoes & Jewelry","boys,clothing,clothes,shoes,jewelry,boys clothing,boys shoes,boys jewelry".split(",")],["fashion-girls","Girls' Clothing, Shoes & Jewelry","girls,clothing,clothes,shoes,jewelry,girls clothing,girls shoes,girls jewelry".split(",")]],B=[["jewelry","Jewelry",["jewelry"]],["shoes","Shoes",["shoes","handbags","sandals","boots"]],["apparel",
"Clothing & Accessories","clothing,clothes,hats,shirts,jacket,wallets,sunglasses".split(",")]];a.createDataArray=function(a,F){var E=[],V=void 0,V=typeof F!=="undefined"&&F.hasOwnProperty("isWayfindingEnabled")&&F.isWayfindingEnabled===1?D:B;v=v.concat(V);a.each(v,function(a){a=v[a];E.push({id:a[0],alias:a[0],keyword:"",categoryName:"",type:"department",name:a[1],triggerWords:a[2],sn:!1})});return E};a.getType=function(){return"department"};a.getMinNumOfChars=function(){return 3};a.getMaxNumOfResults=
function(){return 3};a.logImpression=function(a){ue&&ue.count&&(a="deptiss"+a.replace("-",""),ue.count(a,ue.count(a)+1))};a.buildDepartmentReftagSuffix=function(a){var v="deptiss";v+=a.hasOwnProperty("position")?"_"+a.position:"";return v};return a}()}})})(function(){var E=window.AmazonUIPageJS||P,B=E.attributeErrors;return B?B("RetailSearchAutocompleteAuiAssets"):E}());
;/* RetailSearchClientSideLoggingAuiAssets */
(function(d){d.execute(function(){if(!window.$SearchJS&&window.$Nav)window.$SearchJS=$Nav.make("sx");window.$SearchJS&&($SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"}),$SearchJS.importEvent("jQuery",{global:"jQuery"}),$SearchJS.when("jQuery").run("searchCSL-lib",function(c){c.searchCSL=c.searchCSL||new function(){var b=this,g=[],e=[],d,i,j,f,h=200,k;b.init=function(a,l,c){a&&l&&!d&&(d=a,b.updateRid(l),c&&(h=c))};b.updateRid=function(a){a&&i!=a&&(b.tx(),i=a,j={})};b.addWlt=function(a){if(a){if(a.call&&
(a=a(),!a))return;j[a]||(g.push(a),j[a]=1,b.scheduleTx())}};b.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(e.push(a),b.scheduleTx())};b.scheduleTx=function(){if(h==0)b.tx();else{if(!k){var a=window.onbeforeunload;window.onbeforeunload=function(c){f&&(window.clearInterval(f),f=void 0);b.tx();k=!1;return a&&a.call?a(c):void 0};k=!0}!f&&h>0&&(f=window.setTimeout(function(){f=void 0;b.tx()},h))}};b.tx=function(){if(g.length||e.length){var a="/mn/search/csl?";g.length&&
(a+="rrid="+i+"&cpt="+d+"&ctw="+g.join("|"),g=[]);if(e.length){var b="";c.each(e,function(a,d){b+=d.rid+":";c.each(d.selections,function(a,c){c&&(b+=c+(a!=d.selections.length-1?",":""))});b+=a!=e.length-1?".":""});e=[];b&&(a+=a.charAt(a.length-1)=="?"?"":"&",a+="amabotSelections="+b)}(new Image).src=a}}};$SearchJS.publish("search-csl",c.searchCSL)}))})})(function(){var d=window.AmazonUIPageJS||P,c=d.attributeErrors;return c?c("RetailSearchClientSideLoggingAuiAssets"):d}());